name: Pizzeria Autotests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests
        run: |
          pytest --browser=chrome \
                 --alluredir=allure-results \
                 -v
        continue-on-error: true # чтобы артефакты сохранились даже при падении

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/
          retention-days: 7

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-logs
          path: logs/
          retention-days: 7
